[package]
name = "learn"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]

[[bin]]
name = "001_hello"
path = "001_hello/main.rs"

[[bin]]
name = "002_variables"
path = "002_variables/main.rs"

[[bin]]
name = "003_mutability"
path = "003_mutability/main.rs"

[[bin]]
name = "004_constants"
path = "004_constants/main.rs"

[[bin]]
name = "005_shadowing"
path = "005_shadowing/main.rs"

[[bin]]
name = "006_scalars"
path = "006_scalars/main.rs"

[[bin]]
name = "007_integers"
path = "007_integers/main.rs"

[[bin]]
name = "008_floats"
path = "008_floats/main.rs"

[[bin]]
name = "009_bools"
path = "009_bools/main.rs"

[[bin]]
name = "010_chars"
path = "010_chars/main.rs"

[[bin]]
name = "011_tuples"
path = "011_tuples/main.rs"

[[bin]]
name = "012_arrays"
path = "012_arrays/main.rs"
