[package]
name = "learn"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]

[[bin]]
name = "001_hello"
path = "001_hello/main.rs"

[[bin]]
name = "002_variables"
path = "002_variables/main.rs"

[[bin]]
name = "003_mutability"
path = "003_mutability/main.rs"

[[bin]]
name = "004_constants"
path = "004_constants/main.rs"

[[bin]]
name = "005_shadowing"
path = "005_shadowing/main.rs"
